language: python
python:
      - "3.6"
install:
      - pip install -r requirements.txt
      - pip install pytest-cov
      - pip install coveralls
script:
      - pytest --cov app
after_success:
      - coveralls